sonar.projectKey=naveen3830_ai_stock_prediction
sonar.organization=naveen3830


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=S&P 500 Price Predictor
sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
